backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Index'
        name: 'about'
        filter: {field: 'templateKey', value: 'index-page'}
        create: true
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Intro', name: 'body', widget: 'markdown'}
          - label: 'About'
            name: 'about'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Intro', name: 'body', widget: 'markdown'}
              - label: 'Column 1'
                name: 'column1'
                widget: 'object'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Image', name: 'image', widget: 'image'}
                  - {label: 'Image alt text', name: 'imageAlt', widget: 'string'}
                  - {label: 'Body', name: 'body', widget: 'markdown'}
              - label: 'Column 2'
                name: 'column2'
                widget: 'object'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Image', name: 'image', widget: 'image'}
                  - {label: 'Image alt text', name: 'imageAlt', widget: 'string'}
                  - {label: 'Body', name: 'body', widget: 'markdown'}
              - label: 'Column 3'
                name: 'column3'
                widget: 'object'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Image', name: 'image', widget: 'image'}
                  - {label: 'Image alt text', name: 'imageAlt', widget: 'string'}
                  - {label: 'Body', name: 'body', widget: 'markdown'}
              - label: 'Column 4'
                name: 'column4'
                widget: 'object'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Image', name: 'image', widget: 'image'}
                  - {label: 'Image alt text', name: 'imageAlt', widget: 'string'}
                  - {label: 'Body', name: 'body', widget: 'markdown'}
          - label: 'FAQ'
            name: 'faq'
            widget: 'list'
            fields:
              - label: 'Question'
                name: 'question'
                widget: 'string'
              - label: 'Answer'
                name: 'answer'
                widget: 'markdown'
          - label: 'Footer'
            name: 'footer'
            widget: 'object'
            fields:
              - {label: 'Site description', name: 'description', widget: 'markdown'}
      - folder: 'src/pages/'
        label: 'Page'
        name: 'page'
        filter: {field: 'templateKey', value: 'page'}
        create: true
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Body', name: 'body', widget: 'markdown'}